on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Please enter the valid tag'
        required: true
        default: 'Foo'
      prompt:
        description: 'Please confirm if Entered tag is not the latest and still want to proceed by entering [Y|y]'
        required: true
        default: 'n'
jobs:
    finalizebuild:
            runs-on: [ self-hosted, linux ]
            container: ghcr.io/${{ github.repository }}/Dockerfile
            steps:
              - name: initializing build
                run: |
                    bash root/.scripts/Fbuld.sh ${{ inputs.tag }} ${{ inputs.prompt}}



            
                  