on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Please enter the valid tag'
        required: true
        default: 'Foo'
      prompt:
        description: 'Please confirm if Entered tag is not the latest one and Enter Y/y to proceed:'
        required: true
        default: 'Foo'

